# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/post/create
Content-Type: application/json

{
  "title": "hi",
  "content": "hi there",
  "userId": "1",
  "pictures": null
}

###
PUT http://localhost:8080/post/update/3
Content-Type: application/json

{
  "content": "hi there update"
}

###
DELETE http://localhost:8080/post/delete/3
Accept: application/json

###
GET http://localhost:8080/post/read/3
Accept: application/json

###
GET http://localhost:8080/post/read
Accept: application/json

###