GET http://localhost:8080/user
Accept: application/json

###
GET http://localhost:8080/user/user1
Accept: application/json

###
POST http://localhost:8080/user
Content-Type: application/json

{
    "id": "user4",
    "name": "P.O",
    "email": "krkr444@dgsw"
}

###
PUT http://localhost:8080/user
Content-Type: application/json

{
    "id": "user4",
    "name": "피오",
    "email": "krkr444@dgsw"
}

###
DELETE http://localhost:8080/user/user3
Accept: application/json

###